### PR TITLE
Upgrade rlp library to 0.4.0

### PR DESCRIPTION
**Pull request by sgkim126**
This version removed the dependency on elastic_array.

### CODE REVIEW

**Comment by Remagpie** [comment]
LGTM.
BTW, do we have any plan on migrating to upstream rlp crate?

**Comment by sgkim126** [comment]
@Remagpie https://github.com/CodeChain-io/rlp/commit/2bbe848e6b487248d90ad87ae509b5e9e849bc2d The change was brought from the upstream.

**Comment by Remagpie** [comment]
@sgkim126 I wanted to ask if we have any plan for using paritytech's rlp crate instead of CodeChain/rlp.

**Comment by sgkim126** [comment]
@Remagpie Not possible since we have some more implementation than the upstream implementation.

**Comment by sgkim126** [comment]
> * util/merkle/src/triedb.rs

**Comment by sgkim126** [comment]
I had closed the issue by mistake.

**Pull request merged**
