### PR TITLE
Update document's basic usage section in accordance to recent SDK change

### PR DESCRIPTION
**Pull request by qria**
Looks like the constructor for codechain javascript sdk [changed recently](https://github.com/CodeChain-io/codechain-sdk-js/commit/7150747458c7f8473258eaf78c28c1fdf8f02c65#diff-f41e9d04a45c83f3b6f6e630f10117feR28).

This PR reflects that change to the basic usage section.

### CODE REVIEW

**Comment by qria** [comment]
Identified a few more outdated api usages and fixed it.

There are also a few outside of document, such as [here](https://github.com/CodeChain-io/codechain/blob/9bb2aaaa7d9abd51bd73b36a55a1d71b0396cdb3/test/src/helper/spawn.ts#L48), which looks like it needs fixing, however I am not sure this code is still being used. Doesn't seem like CI or local test runs it. So I did not touch those in the PR.

**Comment by Kais-DkM** [comment]
@qria Could you sign the CLA? You can sign it [here](https://www.clahub.com/agreements/CodeChain-io/codechain).

**Comment by qria** [comment]
@Kais-DkM I've signed the CLA.

**Comment by joojis** [comment]
Thank you for your report. I will fix the broken SDK code soon, including the test you mentioned.

**Pull request merged**
