### PR TITLE
Write WrapCCC tracker to db

### PR DESCRIPTION
**Pull request by HoOngEe**
It fixes https://github.com/CodeChain-io/codechain/issues/1547

### CODE REVIEW

**Comment by sgkim126** [comment]
@HoOngEe Would you check the use case of [Transaction::tracker](https://github.com/CodeChain-io/codechain/blob/master/types/src/transaction/transaction.rs)?
Fixing this function might be better, but please make sure where the function is used.

**Comment by HoOngEe** [comment]
@sgkim126 There are two use cases of [Transaction::tracker](https://github.com/CodeChain-io/codechain/blob/fd0294fba015f1b26dd1c7dc53b8df5685830383/types/src/transaction/transaction.rs#L54). One is for pushing invoice information to block(our target usage) and the other is for calculating `asset_type` in [`devels.rs`](https://github.com/CodeChain-io/codechain/blob/fd0294fba015f1b26dd1c7dc53b8df5685830383/rpc/src/v1/impls/devel.rs#L233).

**Comment by HoOngEe** [comment]
But in the second case, the `asset_type` operates only for `MintAsset` transactions. I think I can safely change the [Transaction::tracker](https://github.com/CodeChain-io/codechain/blob/fd0294fba015f1b26dd1c7dc53b8df5685830383/types/src/transaction/transaction.rs#L54).

**Comment by HoOngEe** [comment]
After the patch, I synchronized local node to Corgi network and got the rpc response previously didn't work.
```
curl http://localhost:8080 -H 'Content-Type: application/json' -d '{"jsonrpc": "2.0", "method": "chain_getTransactionByTracker", "params": ["0x033e49e6e7eeb612694eedfd2b6274c4f0d5b21ce866710c02b4fb8c62f9572b"], "id": null}'
{"jsonrpc":"2.0","result":{"action":{"lockScriptHash":"0x5f5960a7bca6ceeeb0c97bc717562914e7a1de04","parameters":["d5b0e27e1e87d9446b0a45cbe38821ccc1430380"],"payer":"wccqxxz05354l57u877989aus855y0v7wual54n86yf","quantity":"0x3e8","shardId":0,"type":"wrapCCC"},"blockHash":"0x9ae96d65e866ce760617f24a94c2febbc8f8c2c09e9ddb60081a1514f36be1e9","blockNumber":290457,"fee":"0x186a0","hash":"0x71765bbdedf9e22bcb053c41ce5a66852508ca4d0b066d0e943800c7e4719c32","networkId":"wc","result":true,"seq":8,"sig":"0x145e5005e2a4a03ba218a43be01289b8541c81f6eefa781ad024834eebcc3a0719a2a9835e4d94d233dda3e5705e53d74ee7f1518c60019272e37e0162f7a54d01","transactionIndex":1},"id":null}
```

**Comment by sgkim126** [comment]
@HoOngEe Thank you for checking

**Pull request merged**
