### PR TITLE
[WIP] Snapshot sync

### PR DESCRIPTION
**Pull request by foriequal0**
Related issue: https://github.com/CodeChain-io/codechain/issues/144
Depends on: https://github.com/CodeChain-io/codechain/pull/1916

Start from: `Add term_params to Metadata`
 - #1910 Introduce Era (Some commits are cherry-picked from it)
 - #1855 Add state to sync extension
 - #1844 Chunk based snapshot & restore
 - #1862 Fetch snapshot header from peers
 - #1843 Update snapshot message format
 - #1865 Import only desired bootstrap headers
 - #1869 Periodic snapshot
 - #1864 Rename total_score to nonce in sync message
 - #1874 Tendermint periodic snapshot
 - #1872 Collect snapshot chunks from peers
 - #1877 Refactor snapshot e2e test
 - #1873 Add RPC snapshot_getList
 - #1876 Remove unnecessary fields in snapshot e2e test config
 - #1875 Add autoremoving expired snapshot feature
 - #1883 Detect bootstrap header in tendermint worker
 - #1879 Download the full snapshot target block
 - #1914 Change sync extension to update pivot after transitioning to Full
 - #1912 Adjust snapshot timing 
 - #1913 Don't send peer status during the snapshot sync

### CODE REVIEW

**Comment by foriequal0** [comment]
This branch will sit on top of commits that remains after the separation of #1910

**Comment by sgkim126** [comment]
I think there are too many commits in this PR and we still have changes to complete the snapshot sync.
How about merging the code cleanups and refactorings that doesn't change the behavior first?

**Comment by majecty** [comment]
@Remagpie What is the current status of this PR?
What should I do?

**Comment by Remagpie** [comment]
This is just a draft PR for merging snapshot sync into the master branch.
We just have to merge it when we're satisfied with the implementation.
We still have some issues to solve, so we have to leave it for now.

**Comment by sgkim126** [comment]
@majecty Should we keep this issue while we move the development of snapshot sync to Foundry?

**Comment by majecty** [comment]
Let's close this PR.

**Pull request closed without merging**
