### PR TITLE
Update copyright

### PR DESCRIPTION
**Pull request by majecty**

### CODE REVIEW

**Comment by kseo** [comment]
You don't need to update copyrights all at once.

**Comment by majecty** [comment]
@kseo 
Then, how do we change the copyright?

**Comment by kseo** [comment]
@majecty Just update the copyright of the files you modified.

**Comment by sgkim126** [comment]
How about making this PR update the files that have been modified since January 1, and then change others individually?

**Comment by jhs7jhs** [comment]
Moved to #1139.

**Pull request closed without merging**
