### PR TITLE
Add the expiration field to the transactions

### PR DESCRIPTION
**Pull request by jhs7jhs**
Resolves: #247

### CODE REVIEW

**Comment by sgkim126** [comment]
@jhs7jhs Sorry for change the plan, but how about adding an expiration field on TransferAsset transaction, not on Transaction.

**Comment by jhs7jhs** [comment]
@sgkim126 Okay, I'll fix this.

**Comment by jhs7jhs** [comment]
@sgkim126 Implemented and added an e2e test case.

**Comment by jhs7jhs** [comment]
There are some typos and missing lines. Fixing now.

**Comment by jhs7jhs** [comment]
@sgkim126 There's a problem with the implementation. Please see `core/src/miner/miner.rs`.

**Comment by jhs7jhs** [comment]
Fixed the integration test cases.

**Pull request merged**
