### PR TITLE
Migrate from Jest to Mocha and apply tslint

### PR DESCRIPTION
**Pull request by jhs7jhs**
Resolve: #779 
The code was not clear with tslint while using Jest, so I've put applying tslint with the PR.

### CODE REVIEW

**Comment by jhs7jhs** [comment]
There's another way to set timeout. Changing the code.

**Comment by jhs7jhs** [comment]
Moved `this.timeout()` to `it().timeout()`. But `BeforeEach` and `AfterEach` does not have it, so there's still some lines using `this.timeout()`.

**Comment by jhs7jhs** [comment]
Also, the most of the code does not use arrow functions anymore.
Check this: https://mochajs.org/#arrow-functions

**Comment by joojis** [comment]
I'm just wondering, have you tried to check whether a test fails in `after()`?

**Comment by jhs7jhs** [comment]
@joojis 
I heard it's possible to check, but the problem is that we've decided to migrate to Mocha because of some logging problems, and the test cases with `before()` and `after()` are quite hard to read its log files.

**Comment by joojis** [comment]
@jhs7jhs Ok

**Pull request merged**
