### PR TITLE
Add test cases on regular keys

### PR DESCRIPTION
**Pull request by jhs7jhs**
There are two test cases not working because a node do not store failed parcels in current implementation.

### CODE REVIEW

**Comment by jhs7jhs** [comment]
Found several missing lines while merging with the master branch. Fixed.

**Comment by jhs7jhs** [comment]
Implemented remaining cases. (Because #694 is merged)

**Comment by joojis** [comment]
Would you resolve the conflicts? @jhs7jhs

**Comment by jhs7jhs** [comment]
@joojis Resolved

**Pull request merged**
