### PR TITLE
[WIP] Leave log files when sync tests fail, and make them able to download 

### PR DESCRIPTION
**Pull request by jhs7jhs**

### CODE REVIEW

**Comment by joojis** [comment]
@jhs7jhs Could you create another PR for the first commit?

**Comment by jhs7jhs** [comment]
Now leaving a log when a sync test fails.

**Comment by joojis** [comment]
@jhs7jhs I can't find the URLs for uploaded files. https://travis-ci.org/CodeChain-io/codechain/jobs/425193878

**Comment by jhs7jhs** [comment]
@joojis It seems that it's not able to catch exceptions in `BeforeEach()`. And, I think exceptions must be in `test()`. We need to change our convention.

**Comment by jhs7jhs** [comment]
It is not possible to implement now, because it's not able with Jest to delete log files when test succeeds and print the name of log files when test fails.

**Pull request closed without merging**
