### PR TITLE
[WIP] Use release build for integration tests

### PR DESCRIPTION
**Pull request by sgkim126**

### CODE REVIEW

**Comment by jhs7jhs** [comment]
I'll approve after watching the result of Travis CI

**Comment by jhs7jhs** [comment]
Need to add `--enable-devel-api` flag to turn on the developer RPC calls like `devel_startSealing`.

**Comment by jhs7jhs** [comment]
This would work with:
- `--enable-devel-api`
- `--reseal-min-period 0`

**Comment by sgkim126** [comment]
It doesn't make test fast enough.

**Pull request closed without merging**
