### PR TITLE
Load the Tendermint's backup data by calling `handle_message`

### PR DESCRIPTION
**Pull request by majecty**
I found bugs on the backup and recovery of the Tendermint.
There have been a few things that have not been handled while editing other parts of the Tendermint.
I judged that rather than adding the modifications to the backup, calling normal path codes is easier.

### CODE REVIEW

**Comment by sgkim126** [comment]
@majecty Would you explain a bit more?

**Comment by majecty** [comment]
@sgkim126 I added the description.

**Comment by majecty** [comment]
Thanks. You're right. It is used only in `restore`. I'll change the name

**Comment by majecty** [comment]
I fixed the conflict.

**Pull request merged**
