### PR TITLE
Add integration test cases for account RPCs

### PR DESCRIPTION
**Pull request by jhs7jhs**

### CODE REVIEW

**Comment by joojis** [comment]
@jhs7jhs The Travis build failed!

**Comment by jhs7jhs** [comment]
@joojis Could you check it? Failed at the sync test because of timeout. https://travis-ci.org/CodeChain-io/codechain/jobs/422488847

**Comment by joojis** [comment]
I found that the reason was ECONNREFUSED.

It may be one of the problems in the network module, or maybe it crashed before `connect` for other reason. We need to debug this problem.

```
 FAIL  src/integration/sync.test.ts (27.471s)
  ● 2 nodes › A-B diverged › nodeA becomes ahead › It should be synced when A-B connected
    Timeout - Async callback was not invoked within the 10000ms timeout specified by jest.setTimeout.
      91 |       });
      92 | 
    > 93 |       test("It should be synced when A-B connected", async () => {
         |       ^
      94 |         await nodeA.connect(nodeB);
      95 |         await nodeB.waitBlockNumberSync(nodeA);
      96 |         expect(await nodeA.getBestBlockHash()).toEqual(await nodeB.getBestBlockHash());
      at new Spec (node_modules/jest-jasmine2/build/jasmine/Spec.js:85:20)
      at Suite.describe (src/integration/sync.test.ts:93:7)
      at Suite.describe (src/integration/sync.test.ts:87:5)
      at Suite.Object.<anonymous>.describe (src/integration/sync.test.ts:79:3)
      at Object.<anonymous> (src/integration/sync.test.ts:23:1)
  ● 2 nodes › A-B diverged › nodeA becomes ahead › It should be synced when A-B connected
    FetchError: request to http://localhost:8087/ failed, reason: connect ECONNREFUSED 127.0.0.1:8087
      at ClientRequest.<anonymous> (node_modules/node-fetch/lib/index.js:1393:11)
```

**Comment by joojis** [comment]
@jhs7jhs Could you rebase the patch?

**Comment by jhs7jhs** [comment]
@joojis Rebased now. Also:
- added a scenario test on `unlock` & `sign`.
- deleted tests on `remove`

**Pull request merged**
