### PR TITLE
Accept arbitrary string as a chain type

### PR DESCRIPTION
**Pull request by Remagpie**
Fix https://github.com/CodeChain-io/codechain/issues/1839

### CODE REVIEW

**Comment by sgkim126** [comment]
What's the difference between using a cli flag and a config file?

**Comment by Remagpie** [comment]
There should be no difference, and the cli flag overrides the config file's parameter.

**Comment by sgkim126** [comment]
What I asked is why the current code accepts an arbitrary file name for a cli flag, but not for a config file.

**Comment by Remagpie** [comment]
I think our usage of serde's `#[dervie(Deserialize)]` on the type `ChainType` was not valid.
The current implementation shows the following error when I pass a file path as a configuration.
```
Error: "Error while parsing TOML: Error { inner: ErrorInner { kind: Custom, line: None, col: 0, message: \"unknown variant `Custom(./akita.json)`, expected one of `mainnet`, `solo`, `simple_poa`, `tendermint`, `cuckoo`, `blake_pow`, `husky`, `saluki`, `corgi`, `beagle`, `custom`\", key: [\"codechain\", \"chain\"] } }"
```
And if I pass `"custom"` as a configuration, it shows the following error.
```
Error: "Error while parsing TOML: Error { inner: ErrorInner { kind: Custom, line: None, col: 0, message: \"invalid type: unit variant, expected newtype variant\", key: [\"codechain\", \"chain\"] } }
```

I'm not sure about the exact format the serde wants, but it seems that it recognized the `Custom(string)` enum in the `ChainType` as a format.

The cli options are fetched directly as a string with the `clap` library, so it doesn't suffer from the problem above.

**Comment by sgkim126** [comment]
I think it's the difference between `toml` and `serde_json`. I'll try to figure out.

**Comment by sgkim126** [comment]
I confused. CLI doesn't use serde_json. It parses the chain type manually with `FromStr`.
It seems that `sede_derive` doesn't support a fallback field with data for now.

**Comment by Remagpie** [comment]
@sgkim126 Thanks for the review.
BTW, why did you think that we're using `serde_json` for cli option parsing?
We're not using json as a cli argument.

**Pull request merged**
