### PR TITLE
No need to fnd the merge base to check change

### PR DESCRIPTION
**Pull request by sgkim126**
Because it is the purpose of `COMMIT_RANGE` to check the changed files from the master branch, I think we don't need to find the merge base.

### CODE REVIEW

**Comment by foriequal0** [comment]
It'll create false positive when the branch is stale. Long-standing document PR will eat up Travis queue unless we rebase for every change.

**Comment by sgkim126** [comment]
@foriequal0 
How about `COMMIT_RANGE="origin/master..${TRAVIS_COMMIT}"`?
It will not make the false positive for the stale branch.

**Comment by foriequal0** [comment]
I didn't know the differences between `..` and `...`. `..` would be right choice for this.

**Comment by sgkim126** [comment]
https://git-scm.com/book/en/v2/Git-Tools-Revision-Selection#_commit_ranges
The triple-dot contains the commits in the base branch, while the double-dot doesn't.
In other words, `A...B` show all commits that are reachable from `A` or `B` except the commits that are reachable from the merge base of `A` and `B`, while `A..B` show the commits that are reachable from `B` but not reachable from `A`.

**Comment by sgkim126** [comment]
@foriequal0 I modified the commit to use the double dots.

**Pull request merged**
